name: osomerank2
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.12.3
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - amqp==5.2.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - billiard==4.2.0
      - boto3==1.34.129
      - botocore==1.34.129
      - build==1.2.1
      - cachecontrol==0.14.0
      - celery==5.4.0
      - celery-redbeat==2.2.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - crashtest==0.4.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - distlib==0.3.8
      - dnspython==2.6.1
      - docker==7.0.0
      - dulwich==0.21.7
      - email-validator==2.1.1
      - faker==25.0.1
      - fakeredis==2.23.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - fastjsonschema==2.20.0
      - filelock==3.15.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - idna==3.7
      - iniconfig==2.0.0
      - installer==0.7.0
      - jaraco-classes==3.4.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - keyring==24.3.1
      - kombu==5.3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - networkx==3.2.1
      - nltk==3.8.1
      - numpy==1.26.4
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.2.2
      - pexpect==4.9.0
      - pillow==10.2.0
      - pkginfo==1.11.1
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - poetry==1.8.3
      - poetry-core==1.9.0
      - poetry-plugin-export==1.8.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - psycopg2-binary==2.9.9
      - ptyprocess==0.7.0
      - py==1.11.0
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygments==2.18.0
      - pyproject-hooks==1.1.0
      - pytest==8.2.0
      - pytest-celery==1.0.0
      - pytest-docker-tools==3.1.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-memcached==1.62
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - ranking-challenge==1.0.3
      - rapidfuzz==3.9.3
      - redis==5.0.4
      - regex==2024.4.28
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - retry==0.9.2
      - rich==13.7.1
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.30
      - starlette==0.37.2
      - sympy==1.12
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tomlkit==0.12.5
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.4
      - transformers==4.41.2
      - trove-classifiers==2024.5.22
      - typer==0.12.3
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - vine==5.1.0
      - virtualenv==20.26.2
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==12.0
      - xattr==1.1.0
      - yarl==1.9.4
