name: dante
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - black=23.3.0
  - blas=2.122
  - blas-devel=3.9.0
  - bottleneck=1.3.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cython=0.29.36
  - exceptiongroup=1.0.4
  - filelock=3.15.3
  - flake8=4.0.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - hdbscan=0.8.37
  - idna=3.7
  - importlib-metadata=6.0.0
  - iniconfig=1.1.1
  - isort=5.9.3
  - jinja2=3.1.4
  - joblib=1.2.0
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libzlib=1.3.1
  - llvm-openmp=18.1.7
  - markupsafe=2.1.5
  - mccabe=0.7.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=23.1
  - pandas=2.1.1
  - pathspec=0.10.3
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=2.4.0
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pycodestyle=2.8.0
  - pyflakes=2.4.0
  - pysocks=1.7.1
  - pytest=8.2.2
  - python=3.12.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.2.2
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - setuptools=70.1.0
  - six=1.16.0
  - sympy=1.12.1
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - amqp==5.2.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==23.2.0
      - bertopic==0.16.2
      - billiard==4.2.0
      - blinker==1.8.2
      - boto3==1.34.130
      - botocore==1.34.130
      - celery==5.4.0
      - celery-redbeat==2.2.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - dnspython==2.6.1
      - email-validator==2.2.0
      - faker==25.9.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - flask==3.0.3
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - itsdangerous==2.2.0
      - jmespath==1.0.1
      - kombu==5.3.7
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.0.5
      - nltk==3.8.1
      - numba==0.60.0
      - orjson==3.10.5
      - plotly==5.22.0
      - prompt-toolkit==3.0.47
      - psycopg2-binary==2.9.9
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - pynndescent==0.5.13
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - ranking-challenge==2.1.6
      - rbo==0.1.3
      - redis==5.0.6
      - regex==2024.5.15
      - rich==13.7.1
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.31
      - starlette==0.37.2
      - tenacity==8.4.1
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.41.2
      - typer==0.12.3
      - ujson==5.10.0
      - umap-learn==0.5.6
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vine==5.1.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.3
      - yarl==1.9.4
