FROM python:3.12

WORKDIR /app/scorer_worker

# Install Poetry
RUN pip install poetry

# Copy only the necessary files to install dependencies with Poetry
COPY pyproject.toml poetry.lock ./

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

# Copy rankingserver / scorer apps
COPY app/ /app
