# syntax=docker/dockerfile:1

#FROM node:18-alpine
FROM python:3.11
#WORKDIR ~/prosocial_ranking/topic_diversity_training
WORKDIR /app
# COPY . .
# RUN yarn install --production
# RUN make ~/prosocial_ranking/topic_diversity_training
# CMD ["node", "src/index.js"]
#RUN set -xe \
#    && apk add --update py3-pip \
#    && apk add --update python3
#    && apk add --update python3-venv
#RUN python3 -m venv newvenv
# RUN virtualenv venv
#RUN source newvenv/bin/activate
# RUN python3 -m venv newenv
# RUN pip install --upgrade pip
#COPY requirements.txt /tmp/requirements.txt
#RUN pip install -r /tmp/requirements.txt
#COPY data/ /app/
RUN mkdir -p /app/data
COPY data/rockwell_engagement_data_with_partisanship_just_text.csv /app/data/
RUN mkdir -p /app/models
#COPY model/ /app/
COPY requirements.txt /app
COPY config.ini /app
COPY audience_diversity_BERTopic_Rockwell.py /app
#RUN pip install -r requirements.txt
RUN pip install --upgrade numpy
RUN pip install pandas
RUN pip install --upgrade pip setuptools wheel
RUN pip install bertopic --no-cache-dir
RUN pip uninstall hdbscan -y
RUN pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation
RUN pip install boto3
RUN pip install psycopg2
RUN pip install redis
CMD python audience_diversity_BERTopic_Rockwell.py
# EXPOSE 3000